name: YARAGS
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py312h927b8db_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - asgiref=3.10.0=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - backoff=2.2.1=pyhd8ed1ab_1
  - bcrypt=5.0.0=py312hdabe01f_1
  - bibtexparser=1.4.3=pyhd8ed1ab_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py312h9d5906e_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.5=h2466b09_0
  - ca-certificates=2025.10.5=h4c7d964_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - chromadb=1.0.20=py312h8eaa3bc_0
  - click=8.3.0=pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - cpython=3.12.12=py312hd8ed1ab_1
  - cryptography=46.0.3=py312h84d000f_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dlfcn-win32=1.4.2=hac47afa_0
  - dnspython=2.8.0=pyhcf101f3_0
  - durationpy=0.10=pyhd8ed1ab_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - fastapi=0.115.9=pyh29332c3_0
  - fastapi-cli=0.0.16=pyhcf101f3_0
  - feedparser=6.0.12=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - google-auth=2.43.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - grpcio=1.74.1=py312h9256aa6_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hf-xet=1.2.0=py310hfb9af98_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py312he06e257_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=1.1.2=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh7428d3b_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - krb5=1.21.3=hdf4eb48_0
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libcurl=8.17.0=h43ecb02_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libgcc=15.2.0=h1383e82_7
  - libgomp=15.2.0=h1383e82_7
  - libgrpc=1.74.1=h317e13b_1
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libprotobuf=6.31.1=hdcda5b4_2
  - libpulsar=3.7.2=he703cff_1
  - libre2-11=2025.11.05=h0eb2380_0
  - libsqlite=3.51.0=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libstdcxx=15.2.0=h904f734_7
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.5=hfa2b4ca_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h05f76fc_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mkl=2025.3.0=hac47afa_454
  - mmh3=5.2.0=py312hbb81ca0_2
  - monotonic=1.6=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py312h05f76fc_0
  - numpy=2.3.4=py312ha72d056_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - ollama=0.12.10=cpu_hf2b74f5_0
  - ollama-python=0.6.0=pyhd8ed1ab_0
  - onnxruntime=1.22.0=py312h414cfab_0_cpu
  - openssl=3.6.0=h725018a_0
  - opentelemetry-api=1.38.0=pyhd8ed1ab_0
  - opentelemetry-exporter-otlp-proto-common=1.38.0=pyhd8ed1ab_0
  - opentelemetry-exporter-otlp-proto-grpc=1.38.0=pyhd8ed1ab_0
  - opentelemetry-instrumentation=0.59b0=pyhd8ed1ab_0
  - opentelemetry-instrumentation-asgi=0.59b0=pyhd8ed1ab_0
  - opentelemetry-instrumentation-fastapi=0.59b0=pyhd8ed1ab_0
  - opentelemetry-proto=1.38.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.38.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.59b0=pyh3cfb1c2_0
  - opentelemetry-util-http=0.59b0=pyhd8ed1ab_0
  - orjson=3.11.4=py312hdabe01f_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyh8b19718_0
  - posthog=5.4.0=pyhd8ed1ab_0
  - propcache=0.3.1=py312h31fea79_0
  - protobuf=6.31.1=py312hcb3287e_2
  - pulsar-client=3.8.0=py312h0afb00f_1
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybase64=1.4.2=py312he06e257_2
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py312hdabe01f_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pypika=0.48.9=pyhd8ed1ab_1
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyreadline3=3.5.4=py312h2e8e312_2
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h0159041_1_cpython
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python-gil=3.12.12=hd8ed1ab_1
  - python-kubernetes=34.1.0=pyhd8ed1ab_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=py312h05f76fc_0
  - pyzotero=1.7.5=pyhd8ed1ab_0
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - rpds-py=0.28.0=py312hdabe01f_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - sgmllib3k=1.0.0=pyhd8ed1ab_1
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - starlette=0.45.3=pyha770c72_0
  - sympy=1.14.0=pyh04b8f61_5
  - tbb=2022.3.0=hd094cb3_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.13=h2c6b04d_2
  - tokenizers=0.22.1=py312h362b069_1
  - tomli=2.3.0=pyhcf101f3_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3.1=pyha7b4d00_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.3.0=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh5737063_0
  - uvicorn-standard=0.38.0=h5737063_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - watchfiles=1.1.1=py312hb0142fd_0
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py312he5662c2_2
  - wheel=0.45.1=pyhd8ed1ab_1
  - whenever=0.9.3=py312hdabe01f_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=1.17.3=py312he06e257_1
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py312h05f76fc_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py312he5662c2_1
  - zstd=1.5.7=hbeecb71_2
prefix: C:\Users\mamar9317\AppData\Local\miniconda3\envs\YARAGS
